repos:
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
    - id: check-added-large-files
      args: ["--maxkb=5000"]
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

ci:
  autoupdate_schedule: monthly

# you can run `pre-commit autoupdate` to automatically update to the latest version of hooks!
