repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: requirements-txt-fixer


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

ci:
  autoupdate_schedule: monthly

# you can run `pre-commit autoupdate` to automatically update to the latest version of hooks!
