language: python

stages:
    - name: basic tests
    - name: behind Earthdata
    if: branch = master OR commit_message =~ nsidc_tests OR type = cron

jobs:
    include:
        - stage: basic tests
          script: pytest \
          icepyx/tests/test_is2class_inputs.py \
          icepyx/tests/test_is2class_query.py \
          icepyx/tests/test_is2class_methods.py
        
        - stage: behind Earthdata
          script: pytest icepyx/tests/test_is2class_NSIDC-API.py
