# From: https://github.com/uwhackweek/jupyterbook-template/.github/workflows/binder-badge.yml

name: AddBinderBadge
on:
  push:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  add-badge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v2
    - name: print vars
      run: |
        echo $GITHUB_HEAD_REF
        echo $GITHUB_REPOSITORY
        echo $GITHUB_REF
        echo $GITHUB_BASE_REF
        echo ${{ github.head_ref}}
        echo ${{ github.ref}}
        echo ${{ github.base_ref}}

    - name: Comment on PR with Binder link
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          var BRANCH_NAME = process.env.BRANCH_NAME;
          var CONTENT_REPO = process.env.CONTENT_REPO;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/icesat2py/icepyx/main?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252F${CONTENT_REPO}%26urlpath%3Dlab%252Ftree%252Ficepyx%252Fexamples%252F%26branch%3D${BRANCH_NAME}) :point_left: Launch a binder notebook on this branch`
          })
      env:
        BRANCH_NAME: ${{ github.ref }}
        CONTENT_REPO: ${{ github.repository }}