# From: https://github.com/uwhackweek/jupyterbook-template/.github/workflows/binder-badge.yml

name: Binder Badge
on:
  push:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: print vars
      run: |
        echo $GITHUB_HEAD_REF
        echo $GITHUB_REPOSITORY
        echo $GITHUB_REF
        echo $GITHUB_BASE_REF
        echo ${{ github.head_ref}}
        echo ${{ github.ref}}
        echo ${{ github.base_ref}}