name: Binder Badge
on:
  push:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: print vars
      run: |
        echo $PR_HEAD_REF
        echo $PR_HEAD_USERREPO
        echo $GITHUB_HEAD_REF
        echo $GITHUB_REPOSITORY
      env:
        PR_HEAD_REF: ${{ github.head_ref }}
        PR_HEAD_USERREPO: ${{ github.repository }}