# use the flake8 linter to annotate improperly formatted code
name: Run flake8 linter on PRs

on:
  pull_request:
    branches:
      - development
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Annotate PR after running flake8
        uses: TrueBrain/actions-flake8@v2
        with:
          max_line_length: 88
