name: "Integration test"
# NOTE: This runs all integration tests except those that download data.
# It will not automatically run integration tests (some of which require auth)
# on PRs from forks.
# Integration tests that download data are run separately.


on:
  push:
    branches:
      - "main"  # Releases
      - "development"  # Feature PR merges
  pull_request:
    branches:
      - "main"  # Release PRs
      - "development" # Feature PRs
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref to test"
        type: "string"


jobs:
  test:
    name: "Integration test"
    # Do not run on PRs from forks:
    if: "${{ !github.event.pull_request.head.repo.fork }}"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          ref: "${{ inputs.ref }}"

      - uses: "./.github/actions/install-icepyx"
        with:
          python-version: "3.12"

      - name: "Run auth tests"
        env:
          EARTHDATA_USERNAME: "icepyx_devteam"
          EARTHDATA_PASSWORD: "${{ secrets.EARTHDATA_PASSWORD }}"
          NSIDC_LOGIN: "${{ secrets.EARTHDATA_PASSWORD }}"
        run: |
          pytest icepyx/tests/integration --verbose --cov app -m "not downloads_data"

      - name: "Upload coverage report"
        uses: "codecov/codecov-action@v5.4.0"
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
