name: Run linters on PRs

on:
  pull_request:
    branches:
      - development
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run black linter
        uses: psf/black@stable      
      # use the flake8 linter to annotate improperly formatted code
      - name: Annotate PR after running flake8
        uses: TrueBrain/actions-flake8@v2
        with:
          max_line_length: 88
          per-file-ignores:
            icepyx/*/__init__.py:F401
