name: Draw diagrams
on:
  push:
  workflow_dispatch:

jobs:
  diagrams:
    name: Draw diagrams
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: run pyreverse
        run: |
          pip install -r requirements.txt
          pip install icepyx pylint 
          sudo apt-get install graphviz
          pyreverse ./icepyx/core -o svg
          mv ./icepyx/core/*.svg ./doc/source/user_guide/documentation/
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Jessica Scheick
          message: "GitHub PlantUML generation auto-update"
          add: "./doc/source/user_guide/documentation/*"
          ref: "uml_action"  # commits to branch "traffic"
