name: Update UML diagrams
on:
  push:
  workflow_dispatch:

jobs:
  diagrams:
    name: Update UML diagrams
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: set up environment
        run: |
          pip install -r requirements.txt
          pip install icepyx pylint 
          sudo apt-get install graphviz
      - name: run pyreverse
        run: |
          pyreverse ./icepyx/core -o svg
          mv ./*.svg ./doc/source/user_guide/documentation/
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Action
          message: "GitHub action UML generation auto-update"
          add: "./doc/source/user_guide/documentation/*"
          ref: git branch --show-current
